use_frameworks!

platform :ios, '10.0'

target 'KetchSDKWrapperCocoaPod_Example' do
  pod 'KetchSDKWrapperCocoaPod', :path => '../'

  target 'KetchSDKWrapperCocoaPod_Tests' do
    inherit! :search_paths

    
  end
end
